baseurl = "/"
languageCode = "en-us"
title = "高杨梅的世界"
theme = "hugo-creative-portfolio-theme"
#disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  style = "default"
  description = "Describe your website"
  copyright = "&copy;2019 Gaoyangmei"
  sidebarAbout = [
    "My drawing world."

  ]
  email = "gaoymmail@gmail.com"
  
  #[[params.navlinks]]
  #name = "Home"
  #url = "post/"

  [[params.navlinks]]
  name = "Drawing"
  url = "drawing/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [params.social]
  #facebook      = "full page or profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  email         = "gaoymmail@gmail.com"
  #twitter       = "full profile url in twitter"
  #linkedin      = "full profile url in linkedin"
  #stackoverflow = "full profile url in stackoverflow"
  #instagram     = "full profile url in instagram"
  #github        = "full profile url in github.com"
  #youtube       = "full profile url in youtube"
  #whatsapp      = "wa.me service link"
